[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.simple"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "always"
healthcheckPath = "/health"
healthcheckTimeout = 600

[environments.production.variables]
PORT = "8080"
DATABASE_URL = "sqlite:///./kirinvulndb.db"
NVD_API_KEY = "05c32e35-bd2c-4b72-bfb6-1fb0ac7fe0b4"
REDIS_URL = "redis://localhost:6379"
LOG_LEVEL = "INFO"
CVE_COLLECTION_INTERVAL = "21600"
VENDOR_COLLECTION_INTERVAL = "43200" 
COMMUNITY_COLLECTION_INTERVAL = "86400"