[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.simple"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "always"
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[environments.production.variables]
PORT = "8080"
DATABASE_URL = "sqlite:///./kirinvulndb.db"
NVD_API_KEY = "d9b1e4b4-649a-4fac-93e5-fe808def98ec"
REDIS_URL = "redis://localhost:6379"
LOG_LEVEL = "INFO"
CVE_COLLECTION_INTERVAL = "21600"
VENDOR_COLLECTION_INTERVAL = "43200" 
COMMUNITY_COLLECTION_INTERVAL = "86400"